### ISSUE TITLE
Standardize on container metrics for memory usage

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/grafana-dashboards#13]
I see we use `container_memory_working_set_bytes` and `container_memory_rss` for memory listing. We should figure out one and consistently stick to it.

**Comment by minrk** [comment]
A quick googling found [this](https://faun.pub/how-much-is-too-much-the-linux-oomkiller-and-used-memory-d32186f29c9d) (via [SO, of course](https://stackoverflow.com/a/66778814/938949)), which suggests that `container_memory_working_set_bytes` is what we should use if OOM is what we are interested in.
