### ISSUE TITLE
Move support resources to their own dashboard

### ISSUE THREAD

**Issue by minrk** [jupyterhub/grafana-dashboards#25]
The NFS/support bits of the Cluster dashboard don't seem generic to jupyterhub deployments (and pedantically aren't really metrics about the cluster). Maybe move them to a 'support' dashboard? I'm not 100% sure they belong in this repo at all since they seem pretty deployment-specific, but I understand why they're here right now. At least in their own dashboard, they are more easily ignored for deployments where they contain no information.

Motivation: I don't have these, so don't love 2/3 of the Cluster dashboard being a lot of "no data" panels. I expect this would be the case for a majority of deployments.

**Comment by yuvipanda** [comment]
@minrk I was thinking the same! I was thinking we can optionally deploy https://grafana.com/grafana/dashboards/9614, and something similar for prometheus. I do want to make sure we have options for NFS monitoring though. But let's start by splitting it off?

**Comment by yuvipanda** [comment]
We can use https://grafana.com/grafana/dashboards/3662 for prometheus.

**Comment by minrk** [comment]
Yeah, first step to just take the exact same info into its own dashboard makes sense to me. Then I can safely ignore it and you can do whatever you want :)

**Comment by yuvipanda** [comment]
> Then I can safely ignore it and you can do whatever you want :)

+1 :D
