### ISSUE TITLE
Information about memory/cpu etc for the JupyterHub Helm chart's proxy pod

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/grafana-dashboards#44]
While debugging an issue that could relate to the proxy pod, I hoped to find data about the proxy pods memory in these dashboards.

I understand it as that is not yet provided, it would be great to have. @snickell has provided an inspiring example of how it could look in https://github.com/jupyterhub/configurable-http-proxy/issues/388.

**Comment by yuvipanda** [comment]
Fixed by https://github.com/jupyterhub/grafana-dashboards/pull/81
