### ISSUE TITLE
unknown function with name "group"

### ISSUE THREAD

**Issue by underdark456** [jupyterhub/grafana-dashboards#86]
### Bug description
After importing on many dashboards I see the following error:
`bad_data: 8:3: parse error: unknown function with name "group"`

Grafana v. 9.1.0

**Comment by consideRatio** [comment]
If someone reproduce this with grafana 10.4 and recently deployed dashboards, please comment about it here.

**Comment by consideRatio** [comment]
Preliminary closing this
